# Generated by Django 5.0.2 on 2024-02-17 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("zipcode", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="HousingApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temporary", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="MaintenanceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Manager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstName", models.CharField(max_length=100)),
                ("lastName", models.CharField(max_length=100)),
                ("archived", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstName", models.CharField(max_length=100)),
                ("lastName", models.CharField(max_length=100)),
                ("unitId", models.IntegerField()),
                ("dob", models.DateField()),
                ("impairments", models.CharField(max_length=100)),
                ("archived", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ManagerBuilding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "buildingId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Portal.building",
                    ),
                ),
                (
                    "managerId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Portal.manager"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="manager",
            name="managerBuilding",
            field=models.ManyToManyField(
                through="Portal.ManagerBuilding", to="Portal.building"
            ),
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unitNumber", models.CharField(max_length=100)),
                (
                    "buildingId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Portal.building",
                    ),
                ),
                (
                    "maintenanceRequests",
                    models.ManyToManyField(to="Portal.maintenancerequest"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="building",
            name="units",
            field=models.ManyToManyField(to="Portal.unit"),
        ),
        migrations.CreateModel(
            name="UserAccount",
            fields=[
                (
                    "email",
                    models.EmailField(
                        max_length=254, primary_key=True, serialize=False
                    ),
                ),
                ("password", models.CharField(max_length=100)),
                ("admin", models.BooleanField(default=False)),
                ("personId", models.IntegerField()),
                ("twoFactorKey", models.CharField(max_length=100)),
                ("archived", models.BooleanField(default=False)),
                (
                    "maintenanceRequest",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Portal.maintenancerequest",
                    ),
                ),
                (
                    "manager",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Portal.manager",
                    ),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Portal.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserHousingApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "housingApplicationId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Portal.housingapplication",
                    ),
                ),
                (
                    "userId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Portal.useraccount",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="useraccount",
            name="userHousingApplications",
            field=models.ManyToManyField(
                through="Portal.UserHousingApplication", to="Portal.housingapplication"
            ),
        ),
    ]
