# Generated by Django 5.0.2 on 2024-02-17 02:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Portal", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraccount",
            name="personId",
        ),
    ]
