# Generated by Django 5.0.2 on 2024-02-17 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Portal", "0002_remove_useraccount_personid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="maintenanceRequest",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Portal.maintenancerequest",
            ),
        ),
    ]
