# Generated by Django 5.0.2 on 2024-02-17 02:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Portal", "0003_alter_useraccount_maintenancerequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="username",
            field=models.CharField(default="", max_length=50),
        ),
    ]
