# Generated by Django 5.0.2 on 2024-03-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Portal", "0004_alter_building_buildingname"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="unitBedrooms",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="unit",
            name="unitFloor",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="unit",
            name="unitName",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="unit",
            name="unitSize",
            field=models.CharField(default="", max_length=100),
        ),
    ]
