# Generated by Django 5.0.2 on 2024-03-03 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Portal", "0005_unit_unitbedrooms_unit_unitfloor_unit_unitname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenancerequest",
            name="building",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Portal.building",
            ),
        ),
    ]
