# Generated by Django 5.0.2 on 2024-02-17 03:42

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Portal", "0005_alter_useraccount_options_useraccount_date_joined_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="useraccount",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="username",
            field=models.CharField(default="", max_length=50, unique=True),
        ),
    ]
