# Generated by Django 5.0.2 on 2024-03-04 00:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Portal", "0007_maintenancerequest_entry_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenancerequest",
            name="unit",
            field=models.CharField(default="", max_length=100),
        ),
    ]
