# Generated by Django 5.0.2 on 2024-03-04 01:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Portal", "0008_maintenancerequest_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenancerequest",
            name="notes",
            field=models.CharField(default="", max_length=10000),
        ),
    ]
