# Generated by Django 5.0.2 on 2024-03-04 01:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Portal", "0009_maintenancerequest_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenancerequest",
            name="dateCompleted",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
