# Generated by Django 5.0.2 on 2024-03-04 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0010_maintenancerequest_datecompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingapplication',
            name='userId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserHousingApplication',
        ),
    ]
