# Generated by Django 5.0.2 on 2024-03-04 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Portal", "0012_alter_housingapplication_userid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="maintenancerequest",
            name="notes",
        ),
        migrations.CreateModel(
            name="MaintenanceNotes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dateMade", models.DateTimeField(blank=True, null=True)),
                ("notes", models.CharField(default="", max_length=10000)),
                (
                    "maintenanceRequestId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Portal.maintenancerequest",
                    ),
                ),
                (
                    "userId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
