# Generated by Django 5.0.2 on 2024-03-04 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Portal", "0013_remove_maintenancerequest_notes_maintenancenotes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintenancenotes",
            name="maintenanceRequestId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maintenance_notes",
                to="Portal.maintenancerequest",
            ),
        ),
    ]
