# Generated by Django 5.0.2 on 2024-03-08 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0015_maintenancenotes_tenantviewable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='lastName',
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='request',
            field=models.CharField(max_length=10000),
        ),
    ]
