# Generated by Django 5.0.2 on 2024-03-09 03:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Portal", "0016_remove_manager_firstname_remove_manager_lastname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintenancerequest",
            name="status",
            field=models.CharField(default="New", max_length=100),
        ),
    ]
