# Generated by Django 5.0.2 on 2024-03-18 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0017_alter_maintenancerequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='buildingId',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='unitId',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='unitId',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='twoFactorKey',
        ),
        migrations.DeleteModel(
            name='HousingApplication',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
