# Generated by Django 5.0.2 on 2024-03-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Portal", "0018_remove_unit_buildingid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="maintenancerequest",
            name="completed",
        ),
        migrations.AddField(
            model_name="maintenancerequest",
            name="date_submitted",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
