# Generated by Django 5.0.2 on 2024-03-22 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0019_remove_maintenancerequest_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
