# Generated by Django 5.0.2 on 2024-03-23 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0020_remove_useraccount_tenant_delete_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='assigned_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserAccountMaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenanceRequest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portal.maintenancerequest')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
