# Generated by Django 5.0.2 on 2024-04-12 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0023_maintenancerequest_priority'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useraccountmaintenancerequest',
            unique_together={('user_id', 'maintenanceRequest_id')},
        ),
    ]
