# Generated by Django 5.0.2 on 2024-04-15 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0024_alter_useraccountmaintenancerequest_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='address',
        ),
    ]
