# Generated by Django 5.0.2 on 2024-04-15 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Portal", "0025_remove_maintenancerequest_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="maintenance_files/")),
                (
                    "maintenanceRequestId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_files",
                        to="Portal.maintenancerequest",
                    ),
                ),
            ],
        ),
    ]
