# Generated by Django 5.0.2 on 2024-04-15 20:10

import Portal.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0025_remove_maintenancerequest_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=Portal.models.UsernameField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
