# Generated by Django 5.0.2 on 2024-04-15 22:21

import Portal.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Portal", "0026_maintenancefile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintenancefile",
            name="file",
            field=models.FileField(upload_to=Portal.models.maintenance_file_path),
        ),
    ]
