# Generated by Django 5.0.2 on 2024-04-15 20:32

import Portal.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0027_alter_useraccount_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=Portal.models.UsernameField(unique=True),
        ),
    ]
