# Generated by Django 5.0.2 on 2024-04-16 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0027_alter_maintenancefile_file'),
        ('Portal', '0028_alter_useraccount_username'),
    ]

    operations = [
    ]
