# Generated by Django 5.0.2 on 2024-04-17 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0029_merge_20240416_0939'),
        ('Portal', '0029_merge_20240417_0934'),
    ]

    operations = [
    ]
