# Generated by Django 5.0.2 on 2024-04-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0030_merge_20240417_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='managerbuilding',
            name='managerId',
        ),
        migrations.RemoveField(
            model_name='managerbuilding',
            name='buildingId',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.DeleteModel(
            name='ManagerBuilding',
        ),
    ]
