# Generated by Django 5.0.2 on 2024-04-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0031_remove_useraccount_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='building_sort',
            field=models.CharField(default='id', max_length=100),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='paging_count',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='request_sort',
            field=models.CharField(default='id', max_length=100),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='user_sort',
            field=models.CharField(default='id', max_length=100),
        ),
    ]
