# Generated by Django 5.0.2 on 2024-04-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0033_alter_maintenancerequest_entry_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], default='Low', max_length=100),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='New', max_length=100),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='paging_count',
            field=models.PositiveSmallIntegerField(choices=[(10, '10 items per page'), (25, '25 items per page'), (50, '50 items per page'), (100, '100 items per page')], default=25),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='request_sort',
            field=models.CharField(choices=[('id', 'ID'), ('-id', 'ID (Descending)'), ('last_name', 'Last Name'), ('-last_name', 'Last Name (Descending)'), ('title', 'Title'), ('-title', 'Title (Descending)'), ('status', 'Status'), ('-status', 'Status (Descending)'), ('priority', 'Priority'), ('-priority', 'Priority (Descending)'), ('building', 'Building'), ('-building', 'Building (Descending)'), ('unit', 'Unit'), ('-unit', 'Unit (Descending)')], default='id', max_length=100),
        ),
    ]
