name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
          POSTGRES_DB: housingportal
        ports:
          - 6000:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        cd HousingPortal
        pip install -r requirements.txt

    - name: Start PostgreSQL
      run: docker start postgres

    - name: Wait for PostgreSQL to be ready
      run: |
        ./wait-for-it.sh localhost:6000 -t 60
    - name: Run Tests
      run: |
        cd HousingPortal
        python manage.py test
